"""Core API for telemetry-driven differentiable dynamics identification.

Source adapters (``glassbox.io``), benchmark workflows (``glassbox.workflows``),
command-line applications (``glassbox.cli``), live-system boundaries
(``glassbox.integrations``), and research-grade APIs (``glassbox.experimental``)
live in their own subpackages. Keeping them out of the package root makes the
stable API small and prevents a core import from loading experiment code.
"""

from glassbox.belief.adaptation import (
    BeliefUpdateProposal,
    BeliefUpdateReport,
    HorizonEndpointErrorEvidence,
    endpoint_error_evidence_by_horizon,
    propose_dynamics_belief_update,
    recalibrate_predictive_error,
    update_dynamics_belief,
    validate_and_commit_dynamics_belief_update,
)
from glassbox.belief.belief import (
    TANGENT_GROUP_ORDER,
    TANGENT_STATE_ORDER,
    DynamicsBelief,
    EmpiricalErrorSample,
    EmpiricalHorizonPredictiveError,
    ErrorCovarianceScope,
    LocalGaussianParameterBelief,
    LocalParameterInformation,
    PlanAssessment,
    PointParameterBelief,
    PredictiveTrajectory,
    ResolvedLocalGeometry,
    RuntimeDynamicsBelief,
    UnavailableParameterEvidence,
    UnavailablePredictiveError,
    apply_tangent_correction,
    structured_parameter_names,
    structured_parameter_vector,
    with_structured_parameter_vector,
)
from glassbox.belief.belief_io import load_dynamics_belief, save_dynamics_belief
from glassbox.belief.parameter_prior import StructuredParameterPrior
from glassbox.control.nmpc import (
    NMPCController,
    NMPCDiagnostics,
    NMPCResult,
    NMPCWarmStart,
    ReferenceTrajectory,
    SafetyEnvelope,
    SolverPolicy,
    SolveStatus,
    SupportFilterMode,
    TrackingTolerances,
)
from glassbox.core.adapter import TrajectoryAdapter
from glassbox.core.data import (
    RIGID_BODY_STATE_SCHEMA,
    ControlChannel,
    ExogenousChannel,
    ObservationChannel,
    Trajectory,
    TrajectorySpec,
    TrajectoryWindows,
    VehicleConfigurationSpec,
    duration_to_steps,
    load_trajectory_npz,
    make_trajectory_spec,
    save_trajectory_npz,
    split_trajectory,
    trajectory_segment,
    trajectory_windows,
)
from glassbox.core.dynamics import (
    BaseDynamicsParams,
    DynamicsParams,
    FixedWingDynamicsParams,
    ModelParams,
    ResidualDynamicsParams,
    model_family,
    rollout,
    rollout_with_latent,
    step,
    step_with_latent,
)
from glassbox.core.evaluation import (
    aggregate_rollout_metrics,
    rollout_divergence_metrics,
    rollout_metrics,
    windowed_rollout_metrics,
)
from glassbox.core.identification import (
    FitResult,
    RolloutLossConfiguration,
    fit_dynamics,
    fit_dynamics_multi_horizon,
    rollout_loss_configuration,
)
from glassbox.core.runtime import (
    ActuationMap,
    DirectActuationMap,
    ModelValidityEnvelope,
    NonActionableModelError,
    RuntimeDynamicsModel,
    RuntimeModelSpec,
    runtime_spec_from_fit_report,
    runtime_spec_from_trajectory,
)

__all__ = [
    "RIGID_BODY_STATE_SCHEMA",
    "TANGENT_GROUP_ORDER",
    "TANGENT_STATE_ORDER",
    "ActuationMap",
    "BaseDynamicsParams",
    "BeliefUpdateProposal",
    "BeliefUpdateReport",
    "ControlChannel",
    "DirectActuationMap",
    "DynamicsBelief",
    "DynamicsParams",
    "EmpiricalErrorSample",
    "EmpiricalHorizonPredictiveError",
    "ErrorCovarianceScope",
    "ExogenousChannel",
    "FitResult",
    "FixedWingDynamicsParams",
    "HorizonEndpointErrorEvidence",
    "LocalGaussianParameterBelief",
    "LocalParameterInformation",
    "ModelParams",
    "ModelValidityEnvelope",
    "NMPCController",
    "NMPCDiagnostics",
    "NMPCResult",
    "NMPCWarmStart",
    "NonActionableModelError",
    "ObservationChannel",
    "PlanAssessment",
    "PointParameterBelief",
    "PredictiveTrajectory",
    "ReferenceTrajectory",
    "ResidualDynamicsParams",
    "ResolvedLocalGeometry",
    "RolloutLossConfiguration",
    "RuntimeDynamicsBelief",
    "RuntimeDynamicsModel",
    "RuntimeModelSpec",
    "SafetyEnvelope",
    "SolveStatus",
    "SolverPolicy",
    "StructuredParameterPrior",
    "SupportFilterMode",
    "TrackingTolerances",
    "Trajectory",
    "TrajectoryAdapter",
    "TrajectorySpec",
    "TrajectoryWindows",
    "UnavailableParameterEvidence",
    "UnavailablePredictiveError",
    "VehicleConfigurationSpec",
    "aggregate_rollout_metrics",
    "apply_tangent_correction",
    "duration_to_steps",
    "endpoint_error_evidence_by_horizon",
    "fit_dynamics",
    "fit_dynamics_multi_horizon",
    "load_dynamics_belief",
    "load_trajectory_npz",
    "make_trajectory_spec",
    "model_family",
    "propose_dynamics_belief_update",
    "recalibrate_predictive_error",
    "rollout",
    "rollout_divergence_metrics",
    "rollout_loss_configuration",
    "rollout_metrics",
    "rollout_with_latent",
    "runtime_spec_from_fit_report",
    "runtime_spec_from_trajectory",
    "save_dynamics_belief",
    "save_trajectory_npz",
    "split_trajectory",
    "step",
    "step_with_latent",
    "structured_parameter_names",
    "structured_parameter_vector",
    "trajectory_segment",
    "trajectory_windows",
    "update_dynamics_belief",
    "validate_and_commit_dynamics_belief_update",
    "windowed_rollout_metrics",
    "with_structured_parameter_vector",
]
