"""Core API for telemetry-driven differentiable dynamics identification.

Source adapters, benchmark workflows, and command-line applications live in
their respective modules. Keeping them out of the package root makes the
stable API small and prevents a core import from loading experiment code.
"""

from glassbox.adaptation import BeliefUpdateReport, update_dynamics_belief
from glassbox.adapter import TrajectoryAdapter
from glassbox.belief import (
    TANGENT_GROUP_ORDER,
    TANGENT_STATE_ORDER,
    DynamicsBelief,
    EmpiricalErrorSample,
    EmpiricalHorizonPredictiveError,
    LocalGaussianParameterBelief,
    PlanAssessment,
    PointParameterBelief,
    PredictiveTrajectory,
    RuntimeDynamicsBelief,
    UnavailablePredictiveError,
    apply_tangent_correction,
    structured_parameter_names,
    structured_parameter_vector,
    with_structured_parameter_vector,
)
from glassbox.belief_io import load_dynamics_belief, save_dynamics_belief
from glassbox.data import (
    RIGID_BODY_STATE_SCHEMA,
    ControlChannel,
    ExogenousChannel,
    ObservationChannel,
    Trajectory,
    TrajectorySpec,
    TrajectoryWindows,
    VehicleConfigurationSpec,
    duration_to_steps,
    load_trajectory_npz,
    make_trajectory_spec,
    save_trajectory_npz,
    split_trajectory,
    trajectory_segment,
    trajectory_windows,
)
from glassbox.dynamics import (
    BaseDynamicsParams,
    DynamicsParams,
    FixedWingDynamicsParams,
    ModelParams,
    ResidualDynamicsParams,
    model_family,
    rollout,
    rollout_with_latent,
    step,
    step_with_latent,
)
from glassbox.evaluation import (
    aggregate_rollout_metrics,
    rollout_divergence_metrics,
    rollout_metrics,
    windowed_rollout_metrics,
)
from glassbox.identification import (
    FitResult,
    RolloutLossConfiguration,
    fit_dynamics,
    fit_dynamics_multi_horizon,
    rollout_loss_configuration,
)
from glassbox.nmpc import (
    NMPCController,
    NMPCDiagnostics,
    NMPCResult,
    NMPCWarmStart,
    ReferenceTrajectory,
    SafetyEnvelope,
    SolveStatus,
    TrackingTolerances,
)
from glassbox.runtime import (
    ActuationMap,
    DirectActuationMap,
    ModelValidityEnvelope,
    NonActionableModelError,
    RuntimeDynamicsModel,
    RuntimeModelSpec,
    runtime_spec_from_fit_report,
    runtime_spec_from_trajectory,
)

__all__ = [
    "RIGID_BODY_STATE_SCHEMA",
    "TANGENT_GROUP_ORDER",
    "TANGENT_STATE_ORDER",
    "ActuationMap",
    "BaseDynamicsParams",
    "BeliefUpdateReport",
    "ControlChannel",
    "DirectActuationMap",
    "DynamicsBelief",
    "DynamicsParams",
    "EmpiricalErrorSample",
    "EmpiricalHorizonPredictiveError",
    "ExogenousChannel",
    "FitResult",
    "FixedWingDynamicsParams",
    "LocalGaussianParameterBelief",
    "ModelParams",
    "ModelValidityEnvelope",
    "NMPCController",
    "NMPCDiagnostics",
    "NMPCResult",
    "NMPCWarmStart",
    "NonActionableModelError",
    "ObservationChannel",
    "PlanAssessment",
    "PointParameterBelief",
    "PredictiveTrajectory",
    "ReferenceTrajectory",
    "ResidualDynamicsParams",
    "RolloutLossConfiguration",
    "RuntimeDynamicsBelief",
    "RuntimeDynamicsModel",
    "RuntimeModelSpec",
    "SafetyEnvelope",
    "SolveStatus",
    "TrackingTolerances",
    "Trajectory",
    "TrajectoryAdapter",
    "TrajectorySpec",
    "TrajectoryWindows",
    "UnavailablePredictiveError",
    "VehicleConfigurationSpec",
    "aggregate_rollout_metrics",
    "apply_tangent_correction",
    "duration_to_steps",
    "fit_dynamics",
    "fit_dynamics_multi_horizon",
    "load_dynamics_belief",
    "load_trajectory_npz",
    "make_trajectory_spec",
    "model_family",
    "rollout",
    "rollout_divergence_metrics",
    "rollout_loss_configuration",
    "rollout_metrics",
    "rollout_with_latent",
    "runtime_spec_from_fit_report",
    "runtime_spec_from_trajectory",
    "save_dynamics_belief",
    "save_trajectory_npz",
    "split_trajectory",
    "step",
    "step_with_latent",
    "structured_parameter_names",
    "structured_parameter_vector",
    "trajectory_segment",
    "trajectory_windows",
    "update_dynamics_belief",
    "windowed_rollout_metrics",
    "with_structured_parameter_vector",
]
